    CREATE TABLE IF NOT EXISTS Tasks (
        id int generated by default as identity,
        task_create_date timestamp(6) with time zone not null,
        task_description VARCHAR(55),
        task_name VARCHAR(55) not null,
        task_status VARCHAR(55) not null,
        primary key (id)
    );